import { STATUS, SHORT_TITLE } from '../constants';
import { Player } from './types';

const players: Player[] = [
	{
		id: 1,
		title: SHORT_TITLE.GM,
		name: 'Tin Jingyao',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 2,
		title: SHORT_TITLE.GM,
		name: 'Goh, Wei Ming Kevin',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 3,
		title: SHORT_TITLE.IM,
		name: 'Siddharth, Jagadeesh',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 4,
		title: SHORT_TITLE.FM,
		name: 'Susilodinata, Andrean',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 5,
		title: SHORT_TITLE.CM,
		name: 'Wong, Zhenyong Jayden',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 6,
		title: SHORT_TITLE.WGM,
		name: 'Gong, Qianyun',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 7,
		title: SHORT_TITLE.IM,
		name: 'Paciencia, Enrique',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 8,
		title: SHORT_TITLE.GM,
		name: 'Wong, Meng Kong',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 9,
		name: 'Chow, Mon Ben',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 10,
		name: 'Liu, Hongtao',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 11,
		name: 'Ong, Yi Herng Joel',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 12,
		name: 'Ng, Sheng Feng',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 13,
		name: 'Ho, Xinglun Royce',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 14,
		name: 'Tan, Zhong Kai',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 15,
		name: 'Saravanan, Durga',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 16,
		name: 'Teo, Hong Ming',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 17,
		name: 'Fang, Kun',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 18,
		title: SHORT_TITLE.AGM,
		name: 'Kapoor, Satvik',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 19,
		name: 'Cai, Mingzhe',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 20,
		name: 'Cheong, Sue Lyn',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 21,
		name: 'Lee, Jing Xi Jonathan',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 22,
		name: 'Gao, Zhenxi Jerry',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 23,
		name: 'Rice, Lauren',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 24,
		name: 'Lakshminarasimhan, Rahul',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 25,
		name: 'Siddharth, Sai',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 26,
		name: 'Burman, Ray Pritish',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 27,
		name: 'Sanjay, Vasu',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 28,
		name: 'Wong, Shyun Fwu Aldrin',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 29,
		name: 'Yu, Bei Hao',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 30,
		name: 'Ng, Say Liang',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 31,
		name: 'Sreekarthika, Velmurugan',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 32,
		name: 'Rice, Leah',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 33,
		name: 'Pang, Kay Yan Eden',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 34,
		name: 'Vijay, Rege',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
	{
		id: 36,
		name: 'Nainika, Gupta',
		status: STATUS.IN,
		exits: 0,
		isPlaying: true,
	},
];

export const sortedPlayers = players.sort((player1, player2) => {
	if (player1.name > player2.name) {
		return 1;
	}
	return -1;
});
